TestPackages/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$',             'commentry.views.home',  name='home'),
    url(r'^thing/(\d+)/$', 'commentry.views.thing', name='thing'),
    url(r'^thing/(\d+)/(thiswillbeavariable/?)$', 'commentry.views.thing', name='thingy'),

    url(r'^comments/', include('django_comments.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^settings/', include('custom_user.urls')),
    url(r'^viz/', include('viz.urls')),

    url(r'^threed/', include('threed.urls')),

    url(r'^member/$', 'custom_user.views.member_index', name='user_home'),
    url(r'^member/action$', 'custom_user.views.member_action', name='user_action'),

    #enable simple auth
    #url(r'^login/$', 'django.contrib.auth.views.login', name='login'),

    url(r'^admin/', include(admin.site.urls)),
)

products/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'products.views.list',  name='products'),
    #url(r'^all/$', 'products.views.list', name='products-all'),
    url(r'^(?P<slug>[\w-]*)/$', 'products.views.single',  name='single-product'),
)

viz/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$',         'viz.views.index',  name='viz-home'),
    url(r'^projects/$', 'viz.views.projects', name='viz-projects'),


)

products/models.py
from django.core.urlresolvers import reverse
from django.db import models


class Product(models.Model):
    title       = models.CharField(max_length=30, null=False, blank=False, unique=True)
    description = models.TextField(null=True,blank=True)
    price       = models.DecimalField(decimal_places=2, max_digits=100, default=29.99)
    sale_price  = models.DecimalField(decimal_places=2, max_digits=100, null=True, blank=True)
    slug        = models.SlugField(unique=True)
    timestamp   = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated     = models.DateTimeField(auto_now_add=False, auto_now=True)
    active      = models.BooleanField(default=True)

    def __unicode__(self):
        return unicode(self.title)

    def get_price(self):
        return self.price

    def get_absolute_url(self):
        return reverse('single-product', kwargs={'slug':self.slug})


class ProductImage(models.Model):
    product   = models.ForeignKey(Product)
    image     = models.ImageField(upload_to='products/images/')
    featured  = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    updated   = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return unicode(self.product.title)

products/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product


# def index(request):
#     context = {'Products': Product.objects.all()}
#     return render(request, 'products/product.html', context)

def list(request):
    context = {'Products': Product.objects.all()}
    return render(request, 'products/list.html', context)

def single(request, slug):
    context = {'Product': Product.objects.get(slug=slug)}
    return render(request, 'products/detail.html', context)

products/templates/products/base.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
    <div class="col-xs-12">
    <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div>
</div>

{% endblock body %}

products/templates/products/detail.html
{% extends 'products/base.html' %}


{% block body %}

    {{ block.super }}

    <h1>Detail</h1>

    <div class="row">
        {% if Product %}
            <div class="col-sm-6 col-sm-offset-3">
                <div>
                    {{ Product.title }}
                </div>
                {% for image in Product.productimage_set.all %}
                    <div>
                        <img class="img-responsive" src="{{ MEDIA_URL }}{{ image.image }}">
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

{% endblock body %}

products/templates/products/list.html
{% extends 'products/base.html' %}

{% block body %}

    {{ block.super }}

    <h1>All</h1>

    <div class="row">
        {% for product in Products %}

            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div>
                    {{ product.title }}
                </div>
                {% for image in product.productimage_set.all %}
                    <div class="thumbnail">
                        <a href="{{ product.get_absolute_url }}">
                            <img class="img-responsive" src="{{ MEDIA_URL }}{{ image.image }}">
                        </a>
                    </div>
                {% endfor %}
            </div>

        {% endfor %}
    </div>
{% endblock body %}